#!/usr/bin/env python3
# *************************************************************************
#
# Copyright (c) 2024 Andrei Gramakov. All rights reserved.
#
# site:    https://agramakov.me
# e-mail:  mail@agramakov.me
#
# *************************************************************************
import sys
import os

# Get the directory of the script you want to import
script_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../scripts'))

# Add the directory to sys.path
sys.path.append(script_path)

import devtemplate

devtemplate.main()
